# Set ctrl space as the default prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g default-terminal "tmux-256color"
# set -ag terminal-overrides ",xterm-256color:RGB"

# an attempt to fix the nvim ghost cursor issue
# set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'

set-option -g focus-events on

set -g history-limit 50000
set -sg escape-time 10
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Enable vi mode for copy mode and command prompt
setw -g mode-keys vi
set -g status-keys vi
# note these settings do not change how one enters copy mode
# prefix + [
# it is the navigation, searching etc inside copy mode that becomes vim style

# Enable mouse mode
set -g mouse on

# ...or, more traditional: navigate with prefix + hjkl (keeps arrow keys working too)
# bind h select-pane -L
# bind j select-pane -D
# bind k select-pane -U
# bind l select-pane -R

bind S choose-tree -s

# Resize panes with vim keys (repeatable)
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Pane splitting with vim-like mnemonics
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# Copy mode: vim-style selection and yank (requires tmux 2.4+)
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
# bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
#integrate copy mode with system clipboard
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

# toggle pane zoom
bind > resize-pane -Z

bind x kill-pane
bind z kill-window

bind-key r command-prompt -I "#W" "rename-window '%%'"
bind-key R command-prompt -I "#S" "rename-session '%%'"
# bind-key r command-prompt -I "#T" "select-pane -T '%%'"

#create new floating pane
# bind-key f display-popup -E -d "#{pane_current_path}" -w 80% -h 80%
# bind-key f display-popup -E -d "#{pane_current_path}" -w 500 -h 500

set -g status-style "bg=teal,fg=black"
# set -ug status-style

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
# keybindings: pref + I, pref + U, pref + alt + U
set -g @plugin 'tmux-plugins/tmux-resurrect'
# keybindings: pref + C-s, pref + C-r
set -g @plugin 'tmux-plugins/tmux-continuum'
# keybindings: none
set -g @continuum-restore 'on'
set -g @plugin 'Morantron/tmux-fingers'
# keybindings: prefix + F
set -g @plugin 'tmux-plugins/tmux-open'
# keybindings: All in tmux copy mode, o, C-o, S-s
# set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'christoomey/vim-tmux-navigator'
# keybindings: C-h, C-j, C-k, C-l, C-\ 
set -g @plugin 'omerxx/tmux-floax'
# keybindings: pref + p, in floating pane: pref + P, +, -, f, r, e
set -g @floax-width '60%'
set -g @floax-height '60%'

run '~/.tmux/plugins/tpm/tpm'
